services:

  backend:
    container_name: backend
    build: ./backend
    networks:
      - backend_network
      - frontend_network

    volumes:
      - ./backend/teletubbies/:/code/
      - media_volume:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - frontend_network
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "443:443"
    depends_on:
      - backend

volumes:
  media_volume:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge


     # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   networks:
  #     - frontend_network
  #     - backend_network
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d:ro # Nginx konfigürasyon dosyalarını kopyalayın
  #     - ./certs:/etc/ssl/certs:ro # SSL sertifikalarını kopyalayın
  #     - ./certs:/etc/ssl/private:ro # SSL anahtar dosyasını kopyalayın
  #   depends_on:
  #     - frontend

# volumes:
#   postgres_data:
#   media_volume:
#   static_volume:

  # db:
  #   container_name: db
  #   image: postgres:latest
  #   networks:
  #     - backend_network
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - .env