version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend_network

  backend:
    env_file:
      - .env    
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
    networks:
      - backend_network
      - frontend_network
    volumes:
      - ./backend/teletubbies/:/code/
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - frontend_network
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "443:443"
    depends_on:
      - backend

volumes:
  media_volume:
  postgres_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
