services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - env_files/.env_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend_network

  backend:
    container_name: backend
    env_file:
      - env_files/.env_backend
    build:
      context: ./backend
    networks:
      - backend_network
      - frontend_network
    volumes:
      - ./backend/teletubbies/:/code/
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - env_files/.env_frontend
    networks:
      - frontend_network
    volumes:
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "443:443"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - env_files/.env_pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  media_volume:
  postgres_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
