# Generated by Django 4.2 on 2024-04-17 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channellol', '0003_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineuserstatus',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='onlineuserstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
