# Generated by Django 4.2 on 2024-03-31 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendlist',
            name='muted',
            field=models.ManyToManyField(blank=True, related_name='muted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
