# Generated by Django 4.2 on 2024-07-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Default Tournament Name', max_length=100),
        ),
    ]
