# Generated by Django 4.2 on 2024-05-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channellol', '0005_onlineuserstatusprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('game_invite', 'Game Invite'), ('unread_message', 'Unread Message')], max_length=20),
        ),
    ]
