# Generated by Django 4.2 on 2024-07-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_username', models.CharField(max_length=100)),
                ('player2_username', models.CharField(max_length=100)),
                ('player1_score', models.PositiveIntegerField()),
                ('player2_score', models.PositiveIntegerField()),
                ('winner_username', models.CharField(blank=True, max_length=100, null=True)),
                ('match_start_time', models.DateTimeField()),
                ('match_finish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('matches', models.JSONField(default=dict)),
                ('teams', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('round_count', models.PositiveIntegerField()),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_list', to='game.round'),
        ),
    ]
