# Generated by Django 4.2 on 2024-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_mode',
            field=models.CharField(default='normal', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
