# Generated by Django 4.2 on 2024-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_match_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=100)),
                ('inviting', models.CharField(max_length=100)),
            ],
        ),
    ]
