# Generated by Django 4.2 on 2024-08-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlol', '0008_remove_friendlist_muted_friendlist_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateChatMessage',
        ),
    ]
